services:
  gateway:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: gateway/Gateway.Api/Dockerfile
    ports:
      - "80:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTP_PORTS: "8080"
    depends_on:
      - userservice.api
      - catalogservice.api

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"

  mongodb-userservice:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongodb-userservice
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: UserServiceDb
    volumes:
      - mongo_userservice_data:/data/db

  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: services/user-service/UserService.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTP_PORTS: "8080"
      MongoSettings__ConnectionString: "mongodb://root:example@mongodb-userservice:27017/UserServiceDb?authSource=admin"
      MongoSettings__DatabaseName: "UserServiceDb"
      Jwt__Key: "ae55eeaac8de877062ba7c878a31873693ae0f0d9bfb6543abe847cc648e67ac"
      Jwt__Issuer: "Biblioteca"
      Jwt__Audience: "BibliotecaServices"
      Jwt__ExpirationMinutes: "60"
    depends_on:
      - mongodb-userservice

  mongodb-catalogservice:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    container_name: mongodb-catalogservice
    ports:
      - "27018:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: CatalogServiceDb
    volumes:
      - mongo_catalogservice_data:/data/db

  catalogservice.api:
    image: ${DOCKER_REGISTRY-}catalogserviceapi
    build:
      context: .
      dockerfile: services/catalog-service/CatalogService.Api/Dockerfile
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTP_PORTS: "8080"
      MongoSettings__ConnectionString: "mongodb://root:example@mongodb-catalogservice:27018/CatalogServiceDb?authSource=admin"
      MongoSettings__DatabaseName: "CatalogServiceDb"
    depends_on:
      - mongodb-catalogservice
      
volumes:
  mongo_userservice_data:
  mongo_catalogservice_data: